### ISSUE TITLE
NullPointerException   com.sumsub.sns.presentation.screen.base.StateHandleDelegate in getValue

### ISSUE THREAD

**Issue by expcapitaldev** [SumSubstance/idensic-mobile-sdk-sample-android#15]
Crash
SDK version: 1.19.7

Stack trace:

`com.sumsub.sns.presentation.screen.base.StateHandleDelegate in getValue at line 12
com.sumsub.sns.presentation.screen.preview.SNSBaseDocumentPreviewViewModel in getApplicant at line 53
com.sumsub.sns.presentation.screen.preview.photo.SNSPreviewPhotoDocumentViewModel in access$getApplicant at line 52
… sns.presentation.screen.preview.photo.SNSPreviewPhotoDocumentViewModel$onDataIsReadableClicked$1 in invokeSuspend at line 146
kotlin.coroutines.jvm.internal.BaseContinuationImpl in resumeWith at line 33
kotlinx.coroutines.internal.DispatchedContinuationKt in resumeCancellableWith at line 367
kotlinx.coroutines.intrinsics.CancellableKt in startCoroutineCancellable at line 30
kotlinx.coroutines.intrinsics.CancellableKt in startCoroutineCancellable$default at line 25
kotlinx.coroutines.CoroutineStart in invoke at line 110
kotlinx.coroutines.AbstractCoroutine in start at line 126
kotlinx.coroutines.BuildersKt__Builders_commonKt in launch at line 56
kotlinx.coroutines.BuildersKt in launch at line 1
kotlinx.coroutines.BuildersKt__Builders_commonKt in launch$default at line 47
kotlinx.coroutines.BuildersKt in launch$default at line 1
com.sumsub.sns.presentation.screen.preview.photo.SNSPreviewPhotoDocumentViewModel in onDataIsReadableClicked at line 140
com.sumsub.sns.presentation.screen.preview.photo.identity.SNSPreviewIdentityDocumentViewModel in onHandleError at line 194
com.sumsub.sns.core.presentation.BaseFragment in onHandleError at line 66
com.sumsub.sns.presentation.screen.SNSAppActivity$onCreate$$inlined$observeEvent$10 in onChanged at line 635
com.sumsub.sns.presentation.screen.SNSAppActivity$onCreate$$inlined$observeEvent$10 in onChanged at line 76
com.sumsub.sns.core.presentation.base.ActionLiveData in observe$lambda-0 at line 17
com.sumsub.sns.core.presentation.base.ActionLiveData in $r8$lambda$-nfkmNPC34ZgAQsb8eNjdYsDy9A
com.sumsub.sns.core.presentation.base.ActionLiveData$$ExternalSyntheticLambda0 in onChanged at line 4
androidx.lifecycle.LiveData in considerNotify at line 133
androidx.lifecycle.LiveData in dispatchingValue at line 151
androidx.lifecycle.LiveData in setValue at line 309
androidx.lifecycle.MutableLiveData in setValue at line 50
com.sumsub.sns.core.presentation.base.ActionLiveData in setValue at line 25
com.sumsub.sns.presentation.screen.SNSAppViewModel in onHandleError at line 344
com.sumsub.sns.presentation.screen.SNSAppActivity in onErrorAction at line 315
com.sumsub.sns.presentation.screen.error.SNSBaseErrorFragment$onViewCreated$$inlined$observeEvent$1 in onChanged at line 635
com.sumsub.sns.presentation.screen.error.SNSBaseErrorFragment$onViewCreated$$inlined$observeEvent$1 in onChanged at line 76
com.sumsub.sns.core.presentation.base.ActionLiveData in observe$lambda-0 at line 17
com.sumsub.sns.core.presentation.base.ActionLiveData in $r8$lambda$-nfkmNPC34ZgAQsb8eNjdYsDy9A
com.sumsub.sns.core.presentation.base.ActionLiveData$$ExternalSyntheticLambda0 in onChanged at line 4
androidx.lifecycle.LiveData in considerNotify at line 133
androidx.lifecycle.LiveData in dispatchingValue at line 151
androidx.lifecycle.LiveData in setValue at line 309
androidx.lifecycle.MutableLiveData in setValue at line 50
com.sumsub.sns.core.presentation.base.ActionLiveData in setValue at line 25
com.sumsub.sns.presentation.screen.error.SNSBaseErrorViewModel in onCloseClicked at line 22
com.sumsub.sns.presentation.screen.error.network.SNSNetworkErrorFragment in onViewCreated$lambda-0 at line 49
com.sumsub.sns.presentation.screen.error.network.SNSNetworkErrorFragment in $r8$lambda$rfb803Tb2fnM9OtNj-ez2o2f_H4
com.sumsub.sns.presentation.screen.error.network.SNSNetworkErrorFragment$$ExternalSyntheticLambda0 in onClick at line 2
android.view.View in performClick at line 7503
com.google.android.material.button.MaterialButton in performClick at line 1119
android.view.View in performClickInternal at line 7480
android.view.View in access$3600 at line 813
android.view.View$PerformClick in run at line 28445
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loop at line 223
android.app.ActivityThread in main at line 7989
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 635
com.android.internal.os.ZygoteInit in main at line 947`

Android 11 from my information. Do not see for other Android SDK versions.
Also I think crash related to 1.27.0 too because can not find information about it

**Comment by palmut** [comment]
Please, update to the latest version 1.27.

**Comment by expcapitaldev** [comment]
thanks!, maybe you can share changelog with current bug?

**Comment by palmut** [comment]
https://developers.sumsub.com/msdk/android/changelog.html

**Comment by expcapitaldev** [comment]
thanks.I expected to see specific information regarding this crash.
