### ISSUE TITLE
SNSException$Network   com.sumsub.sns.core.data.adapter.network.c$a in onFailure: java.net.UnknownHostException: Unable to resolve host "api.sumsub.com": No address associated with hostname

### ISSUE THREAD

**Issue by expcapitaldev** [SumSubstance/idensic-mobile-sdk-sample-android#18]
SDK version: 1.27.0 , see https://developers.sumsub.com/msdk/plugins/cordova/changelog.html

Stack trace:

**SNSException$Network**: java.net.UnknownHostException: Unable to resolve host "api.sumsub.com": No address associated with hostname
`
com.sumsub.sns.core.data.adapter.network.c$a in onFailure at line 1
retrofit2.OkHttpCall$1 in callFailure at line 142
retrofit2.OkHttpCall$1 in onFailure at line 137
okhttp3.internal.connection.RealCall$AsyncCall in run at line 525
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1145
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 644
java.lang.Thread in run at line 1012
`

**UnknownHostException**: Unable to resolve host "api.sumsub.com": No address associated with hostname
`
java.net.Inet6AddressImpl in lookupHostByName at line 156
java.net.Inet6AddressImpl in lookupAllHostAddr at line 103
java.net.InetAddress in getAllByName at line 1152
okhttp3.Dns$Companion$DnsSystem in lookup at line 49
okhttp3.internal.connection.RouteSelector in resetNextInetSocketAddress at line 169
okhttp3.internal.connection.RouteSelector in nextProxy at line 131
okhttp3.internal.connection.RouteSelector in next at line 73
okhttp3.internal.connection.ExchangeFinder in findConnection at line 205
okhttp3.internal.connection.ExchangeFinder in findHealthyConnection at line 106
okhttp3.internal.connection.ExchangeFinder in find at line 74
okhttp3.internal.connection.RealCall in initExchange$okhttp at line 255
okhttp3.internal.connection.ConnectInterceptor in intercept at line 32
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.cache.CacheInterceptor in intercept at line 95
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.http.BridgeInterceptor in intercept at line 83
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.http.RetryAndFollowUpInterceptor in intercept at line 76
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.logging.HttpLoggingInterceptor in intercept at line 154
com.sumsub.sns.core.data.network.interceptor.b in intercept at line 11
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
com.sumsub.sns.core.data.network.interceptor.c in intercept at line 7
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
com.sumsub.sns.core.data.network.interceptor.a in intercept at line 35
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.connection.RealCall in getResponseWithInterceptorChain$okhttp at line 201
okhttp3.internal.connection.RealCall$AsyncCall in run at line 517
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1145
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 644
java.lang.Thread in run at line 1012
`

**GaiException**: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
`
libcore.io.Linux in android_getaddrinfo
libcore.io.ForwardingOs in android_getaddrinfo at line 133
libcore.io.BlockGuardOs in android_getaddrinfo at line 222
libcore.io.ForwardingOs in android_getaddrinfo at line 133
java.net.Inet6AddressImpl in lookupHostByName at line 135
java.net.Inet6AddressImpl in lookupAllHostAddr at line 103
java.net.InetAddress in getAllByName at line 1152
okhttp3.Dns$Companion$DnsSystem in lookup at line 49
okhttp3.internal.connection.RouteSelector in resetNextInetSocketAddress at line 169
okhttp3.internal.connection.RouteSelector in nextProxy at line 131
okhttp3.internal.connection.RouteSelector in next at line 73
okhttp3.internal.connection.ExchangeFinder in findConnection at line 205
okhttp3.internal.connection.ExchangeFinder in findHealthyConnection at line 106
okhttp3.internal.connection.ExchangeFinder in find at line 74
okhttp3.internal.connection.RealCall in initExchange$okhttp at line 255
okhttp3.internal.connection.ConnectInterceptor in intercept at line 32
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.cache.CacheInterceptor in intercept at line 95
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.http.BridgeInterceptor in intercept at line 83
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.http.RetryAndFollowUpInterceptor in intercept at line 76
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.logging.HttpLoggingInterceptor in intercept at line 154
com.sumsub.sns.core.data.network.interceptor.b in intercept at line 11
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
com.sumsub.sns.core.data.network.interceptor.c in intercept at line 7
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
com.sumsub.sns.core.data.network.interceptor.a in intercept at line 35
okhttp3.internal.http.RealInterceptorChain in proceed at line 109
okhttp3.internal.connection.RealCall in getResponseWithInterceptorChain$okhttp at line 201
okhttp3.internal.connection.RealCall$AsyncCall in run at line 517
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1145
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 644
java.lang.Thread in run at line 1012
`

**Comment by olkazmin** [comment]
what is the exact problem here?
Error in the log?

**Comment by expcapitaldev** [comment]
Error in the log and from my log looks like app crashed

**Comment by olkazmin** [comment]
SDK handles the network errors internally. It should NOT crash.
Can you provided a more specific info about scenario that leads to a crash?

**Comment by expcapitaldev** [comment]
unfortunately I can not, it is error from Sentry
