### ISSUE TITLE
RuntimeException Canvas: trying to draw too large(108822528bytes) bitmap.

### ISSUE THREAD

**Issue by expcapitaldev** [SumSubstance/idensic-mobile-sdk-sample-android#19]
SDK version: 1.27.0 , see https://developers.sumsub.com/msdk/plugins/cordova/changelog.html

Stack trace:

`
android.graphics.RecordingCanvas in throwIfCannotDraw at line 266
android.graphics.BaseRecordingCanvas in drawBitmap at line 94
android.graphics.drawable.BitmapDrawable in draw at line 549
android.widget.ImageView in onDraw at line 1446
android.view.View in draw at line 23354
android.view.View in updateDisplayListIfDirty at line 22181
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
androidx.constraintlayout.widget.ConstraintLayout in dispatchDraw at line 1994
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in draw at line 23361
android.view.View in updateDisplayListIfDirty at line 22181
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
androidx.coordinatorlayout.widget.CoordinatorLayout in drawChild at line 1277
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
androidx.fragment.app.FragmentContainerView in drawChild at line 268
android.view.ViewGroup in dispatchDraw at line 4380
androidx.fragment.app.FragmentContainerView in dispatchDraw at line 256
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in draw at line 23361
android.view.View in updateDisplayListIfDirty at line 22181
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in updateDisplayListIfDirty at line 22172
android.view.View in draw at line 23071
android.view.ViewGroup in drawChild at line 4619
android.view.ViewGroup in dispatchDraw at line 4380
android.view.View in draw at line 23361
com.android.internal.policy.DecorView in draw at line 847
android.view.View in updateDisplayListIfDirty at line 22181
android.view.ThreadedRenderer in updateViewTreeDisplayList at line 682
android.view.ThreadedRenderer in updateRootDisplayList at line 688
android.view.ThreadedRenderer in draw at line 786
android.view.ViewRootImpl in draw at line 4877
android.view.ViewRootImpl in performDraw at line 4576
android.view.ViewRootImpl in performTraversals at line 3779
android.view.ViewRootImpl in doTraversal at line 2506
android.view.ViewRootImpl$TraversalRunnable in run at line 9478
android.view.Choreographer$CallbackRecord in run at line 1323
android.view.Choreographer$CallbackRecord in run at line 1331
android.view.Choreographer in doCallbacks at line 964
android.view.Choreographer in doFrame at line 878
android.view.Choreographer$FrameDisplayEventReceiver in run at line 1306
android.os.Handler in handleCallback at line 942
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 204
android.os.Looper in loop at line 291
android.app.ActivityThread in main at line 8129
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 588
com.android.internal.os.ZygoteInit in main at line 1019
`

**Comment by olkazmin** [comment]
What screen causes the crash or at which step does it happen?

**Comment by expcapitaldev** [comment]
{
screen: SNSAppActivity, 
state: resumed
}

RuntimeException: Canvas: trying to draw too large(108822528bytes) bitmap.
RuntimeException
 
android.graphics.RecordingCanvas in throwIfCannotDraw

New
Level: Fatal
Unhandled
Canvas: trying to draw too large(108822528bytes) bitmap.

**Comment by olkazmin** [comment]
not enough info still. Can provide screenshot or a video catpure of the whole identification process that leads to crash?

**Comment by expcapitaldev** [comment]
unfortunately I can not
