### ISSUE TITLE
App content: Foreground services permission issue when I submit app to Google Play review

### ISSUE THREAD

**Issue by kimipeng** [SumSubstance/idensic-mobile-sdk-sample-android#27]
sumsub android.permission.RECORD_AUDIO causes google app submission to ask for video to explain how you going to use it.
Is it still necessary?

```
Your app uses the FOREGROUND_SERVICE_MICROPHONE permission. You can only use this permission if your app performs tasks noticeable to the user when they're not directly interacting with your app.

Microphone
What tasks require your app to use the FOREGROUND_SERVICE_MICROPHONE permission?
```
How do I fix it?
Do I need declare the permissions to AndroidManifest?

**Comment by olkazmin** [comment]
If speaking about this particular demo app the FOREGROUND_SERVICE_MICROPHONE comes from `videoident` dependancy

Recording audio comes from two places:
- videoident
- one of the verification steps is a part of the main library module and it requires sound recording. So it is normal
for us to declare this permission
