### ISSUE TITLE
Build Error after update to the latest version 1.20.0

### ISSUE THREAD

**Issue by sreejith89** [SumSubstance/idensic-mobile-sdk-sample-android#9]
In Android we can't able to update to the  latest version 1.20.0. Since the build was failed after updating to the latest version. We couldn't able resolve the error which was getting when we tried to take the build. Error occurred:  "Unsupported class file major version 59".

Please look at the below logs,

> Task :app:checkDebugDuplicateClasses FAILED
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform bcprov-jdk18on-1.71.jar (org.bouncycastle:bcprov-jdk18on:1.71) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\Accubits\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk18on\1.71\943e8d0c2bd592ad78759c39d6f749fafaf29cf4\bcprov-jdk18on-1.71.jar.
         > Failed to transform 'C:\Users\Accubits\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk18on\1.71\943e8d0c2bd592ad78759c39d6f749fafaf29cf4\bcprov-jdk18on-1.71.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

>Unsupported class file major version 59

**Comment by palmut** [comment]
You need to add Bouncy Castle library to the jetifier blacklist in the android/gradle.properties :
android.jetifier.blacklist=bcprov-jdk17on

**Comment by sreejith89** [comment]
Which I already added still the issue persist

**Comment by palmut** [comment]
Which version of Java are you using?

**Comment by sreejith89** [comment]
VERSION_1_8

**Comment by sreejith89** [comment]
Please check the below image
<img width="726" alt="java version" src="https://user-images.githubusercontent.com/43566427/195066350-0e40cff7-d7b3-4245-8732-4dad3b224d7f.PNG">

**Comment by sreejith89** [comment]
Please check this as well,

PS C:\Users\Accubits\StudioProjects\dexa-coin-android> java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

**Comment by palmut** [comment]
Please, make sure you have correctly added bcprov-jdk18on to the blacklist. Also, try to disable Jetifier.

**Comment by sreejith89** [comment]
let me check, once again.

**Comment by sreejith89** [comment]
Sorry Palmut,

We cannot disable Jetifier since we are using it in our project for image crop and resize as well

**Comment by sreejith89** [comment]
Could you please check my gradle.properties file

**Comment by sreejith89** [comment]
Could you please check my gradle.properties file

# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
#org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app"s APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
android.jetifier.blacklist=bcprov-jdk17on
# Kotlin code style for this project: "official" or "obsolete":
#kotlin.code.style=official
kapt.use.worker.api=false
#kapt.incremental.apt=false
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

**Comment by palmut** [comment]
please replace 
android.jetifier.blacklist=bcprov-jdk17on
with 
android.jetifier.blacklist=bcprov-jdk18on

**Comment by sreejith89** [comment]
Not getting "Unsupported class file major version 59" error, instead build fails with below error

The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.lifecycle:lifecycle-livedata-ktx:2.5.0.
AAR metadata file: C:\Users\Accubits\.gradle\caches\transforms-2\files-2.1\9571ec265c10802706151cd55bed2f8e\jetified-lifecycle-livedata-ktx-2.5.0\META-INF\com\android\build\gradle\aar-metadata.properties.

**Comment by palmut** [comment]
Yes, you need to set compileSDK to the latest API 33.

**Comment by sreejith89** [comment]
ok, let me check and update.

**Comment by sreejith89** [comment]
An error occurred in Class AppViewModelFactory, "Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option"

**Comment by palmut** [comment]
Sorry, I don't think the AppViewModelFactory is a part of SumSub Android Mobile SDK

**Comment by palmut** [comment]
The latest version of Android SDK is required by Google Jetpack libraries.
